services:
  db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_PWD=duda123  # Hardcoded password

  tomcat:
    build: .
    container_name: tomcat-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
